### ISSUE TITLE
Missing Airspace integration in FlightValidator

### ISSUE THREAD

**Issue by Phoenix1355** [TeamSWT7/02-AirTrafficMonitoring#25]
Det er meningen at Airspace klassen skal integreres i systemet. Denne skal have information omkring længde, bredde og højde.

Evt. kig på klassediagrammet igen. Den ligger der inde med properties og methods.

https://github.com/TeamSWT7/02-AirTrafficMonitoring/blob/b0f5115c2ac35a8d13f9abd81f3d438ea6971640/AirTrafficMonitoring/AirTrafficMonitoring/FlightValidator.cs#L19-L36

**Comment by Phoenix1355** [comment]
Dette er lige en Issue test for at se hvordan det virker. Du må meget gerne implementere det @Daxelmac, men det er ikke nødvendigt. Det er mest bare fordi at det er meget skalérbart end den løsning vi har nu (som er lidt for hardcoded IMO)

**Comment by Phoenix1355** [comment]
Det skal rettes til noget i stil alla:
```csharp
foreach (var flight in _flights)
{
    if (flight.position.x > airspace.x + airspace.width || flight.position.x < airspace.x) 
    {
        _flights.Remove(flight); 
    }

    if (flight.position.y > airspace.y + airspace.length || flight.position.y < airspace.y) 
    { 
        _flights.Remove(flight); 
    } 
  
    if (flight.position.z > airspace.z + airspace.height || flight.position.z < airspace.z) 
    { 
        _flights.Remove(flight); 
    } 
 } 
```

**Comment by Daxelmac** [comment]
This has been resolved
